name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.13.1'

      - name: Go Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go

      - name: Docker Build and Save
        run: |
          docker build -t simple-server .
          docker save -o simple-server.tar simple-server

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: simple-server.tar
