name: Build

on:
  push:
    branches: [main]

jobs:
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '^1.13.1'

    - name: Go Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go

    - name: Docker Build and Save
      run: |
        docker build -t server .
        docker save -o server.tar sever

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: server
        path: server
